# Generated by Django 4.2.2 on 2023-07-22 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authn', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='examuser',
            name='role',
            field=models.CharField(choices=[('Deanship', 'Deanship'), ('ExamDepatment', 'ExamDepatment'), ('PresidencyUniversity', 'PresidencyUniversity')]),
        ),
    ]
